# Generated by Django 4.0.4 on 2022-05-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('installmentSize', models.FloatField()),
                ('installment_1', models.FloatField()),
                ('installment_2', models.FloatField()),
                ('installment_3', models.FloatField()),
                ('installment_4', models.FloatField()),
                ('installment_5', models.FloatField()),
                ('installment_6', models.FloatField()),
                ('installment_7', models.FloatField()),
                ('installment_8', models.FloatField()),
                ('installment_9', models.FloatField()),
                ('installment_10', models.FloatField()),
                ('installment_11', models.FloatField()),
            ],
        ),
    ]
